openapi: 3.0.4
info:
  title: IATI Register Your Data API
  description: |-
    This API provides access to the IATI Registry primarily for the purposes of
    making changes to the metadata and URLs in the registry.  It is not
    intended for public access to obtain lists of datasets and reporting
    organisations.

    # Authentication and Authorisation
    Almost all endpoints are only accessible with authorisation.  Most
    providers will need to provide an access token obtained via OpenID Connect
    from IATI Single Sign On (SSO). Access via an OAuth 2.0 Client Credentials
    grant is also possible.  Both access tokens will be scoped to provide
    appropriate access to the API and the required scopes should be requested
    from the identity server. The access token must be forwarded in each
    request to the API as a `Bearer` token in the `Authentication` header.

    ## OpenID Connect (OIDC)
    The diagram below illustrates the general sequence of actions from starting
    the authentication process with SSO to making an API call.  The [details of
    the OIDC flow can be found elsewhere
    ](https://infosec.mozilla.org/guidelines/iam/openid_connect.html) and are
    not repeated here.  It is **strongly recommended** that providers use a
    well-tested and robust OIDC library for communication with the identity
    server, e.g., [mozilla-django-oidc
    ](https://github.com/mozilla/mozilla-django-oidc) for applications
    developed in Django.

    ![Diagram of typical flow](images/sso-sequence.png)

    Scopes control access to make API calls and it is important to check that
    the access token contains the scopes you have requested.  Authorisation to
    access individual resources is controlled separately via an internal *fine-
    grained authorisation* mechanism.

    After you receive an access token you should verify it's signature before
    further use.  Again, a well-tested an robust OIDC library should be able
    to do this for you.

    ## Client Credentials (OAuth 2.0)
    Providers who have specific machine-to-machine needs will be able to apply
    for access via a client credentials OAuth 2.0 grant.  You will be provided
    with a `client_id` and `client_secret` that will be exchanged for an access
    token at the identity server OAuth 2.0 token endpoint.  The appropriate
    scopes must be requested for the calls you wish to make.  These scopes will
    control access to make API calls and it is important to check that the
    access token contains the scopes you have requested.  A given `client_id`
    will be configured to access a single organisation and will have
    administrator level access to that organisation.
  contact:
    email: support@iatistandard.org
  license:
    name: GNU Affero General Public Licence 3.0
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"
  version: 1.0.0
servers:
  - url: "https://registry.iatistandard.org/api/v1"
  - url: "https://dev.registry.iatistandard.org/api/v1"
# ===============================================================
#
# Endpoints
#
# ===============================================================
paths:
  #
  # Reporting orgs resource endpoints
  #
  /reporting-orgs:
    get:
      summary: Get a list of all reporting orgs that the user has access to.
      description: >-
        Get reporting orgs (and basic fields) that the caller has access to.  If the caller has no organisation
        authorisation then an empty list will be returned.
      parameters:
        - name: include_org_meta
          in: query
          description: >-
            Whether to include all organisation metadata with each record.  By default only returns the name and IATI
            organisation identifier of an organisation.
          required: false
          schema:
            type: string
            default: "no"
            enum:
              - "yes"
              - "no"
        - name: include_org_actions
          in: query
          description: Whether to include all organisation actions with each record.  By default does not return any.
          required: false
          schema:
            type: string
            default: "no"
            enum:
              - "yes"
              - "no"
      responses:
        "200":
          description: Successfully returned list of organisations.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportingOrgList"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:reporting_org"
        - openIdConnect:
            - ryd
            - "ryd:reporting_org"
      tags:
        - Reporting Orgs
    post:
      summary: Create a new organisation.
      description: Create a new organisation.
      requestBody:
        description: Create a new organisation.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportingOrgCreateableData"
      responses:
        "201":
          description: Organisation created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportingOrgCreated"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - openIdConnect:
            - ryd
            - "ryd:reporting_org"
            - "ryd:reporting_org:create"
      tags:
        - Reporting Orgs
  "/reporting-orgs/{oid}":
    get:
      summary: Get detailed information about an organisation.
      parameters:
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        - name: include_org_actions
          in: query
          description: Whether to include all organisation actions with the response.  By default does not.
          required: false
          schema:
            type: string
            default: "no"
            enum:
              - "yes"
              - "no"
      responses:
        "200":
          description: Successfully retrieved organisation details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportingOrgRead"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/OrgNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:reporting_org"
        - openIdConnect:
            - ryd
            - "ryd:reporting_org"
      tags:
        - Reporting Orgs
    patch:
      summary: Update information about an organisation
      parameters:
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        - name: include_org_actions
          in: query
          description: Whether to include all organisation actions with the response.  By default does not.
          required: false
          schema:
            type: string
            default: "no"
            enum:
              - "yes"
              - "no"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportingOrgUpdateableData"
      responses:
        "200":
          description: Successfuly updated organisation record.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportingOrgRead"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/OrgNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:reporting_org"
            - "ryd:reporting_org:update"
        - openIdConnect:
            - ryd
            - "ryd:reporting_org"
            - "ryd:reporting_org:update"
      tags:
        - Reporting Orgs
    delete:
      summary: Delete an organisation.
      parameters:
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
      responses:
        "200":
          description: Successfully deleted organisation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                status: success
                error: null
                data: null
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/OrgNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:reporting_org:delete"
        - openIdConnect:
            - ryd
            - "ryd:reporting_org:delete"
      tags:
        - Reporting Orgs
  "/reporting-orgs/{oid}/users":
    get:
      summary: Get list of users associated with this organisation.
      parameters:
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
      responses:
        "200":
          description: Successfully returned list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserList"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/OrgNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - openIdConnect:
            - ryd
            - "ryd:reporting_org:users"
      tags:
        - Reporting Orgs
        - Users
  "/reporting-orgs/{oid}/datasets":
    get:
      summary: Get list of datasets associated with this organisation.
      parameters:
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        - name: include_dataset_actions
          in: query
          description: Whether to include all dataset actions with each record.  By default does not return any.
          required: false
          schema:
            type: string
            default: "no"
            enum:
              - "yes"
              - "no"
      responses:
        "200":
          description: Successfully returned list of datasets.
          content:
            application/json:
              schema:
                type: array
                items:
                  # type: object
                  $ref: "#/components/schemas/DatasetList"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/OrgNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:datasets"
        - openIdConnect:
            - ryd
            - "ryd:datasets"
      tags:
        - Reporting Orgs
        - Datasets
      #
      # User-focused resource endpoints
      #
  "/users/{uid}/reporting-org":
    post:
      summary: >-
        Apply to be associated with an organisation.  Will by default be pending until approved by an admin of that
        organisation.
      parameters:
        - name: uid
          in: path
          description: UUID of user.
          required: true
          schema:
            type: string
            format: uuid
            example: 6423b556-73de-4969-a2f1-91a38bca92b3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oid:
                  type: string
                  format: uuid
                  example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
      responses:
        "200":
          description: Successfully marked user as pending approval with an organisation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                status: success
                error: null
                data: null
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - openIdConnect:
            - ryd
            - "ryd:reporting_org:users"
      tags:
        - Users
  "/users/{uid}/reporting-org/{oid}":
    put:
      summary: Change the user role for a user in a given organisation.
      parameters:
        - name: uid
          in: path
          description: UUID of user.
          required: true
          schema:
            type: string
            format: uuid
            example: 6423b556-73de-4969-a2f1-91a38bca92b3
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  example: admin
      responses:
        "200":
          description: Successfully changed user role.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                status: success
                error: null
                data: null
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - openIdConnect:
            - ryd
            - "ryd:reporting_org:users:update"
      tags:
        - Users
    delete:
      summary: Remove a user from an organisation.  This call will not remove the user's account.
      parameters:
        - name: uid
          in: path
          description: UUID of user.
          required: true
          schema:
            type: string
            format: uuid
            example: 6423b556-73de-4969-a2f1-91a38bca92b3
        - name: oid
          in: path
          description: UUID of organisation.
          required: true
          schema:
            type: string
            format: uuid
            example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
      responses:
        "200":
          description: Successfully marked user as pending approval with an organisation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                status: success
                error: null
                data: null
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - openIdConnect:
            - ryd
            - "ryd:reporting_org:users:update"
      tags:
        - Users
      #
      # Dataset-focused resource endpoints
      #
  /datasets:
    post:
      summary: Add a new dataset to an organisation.
      description: Replaces the `/package_create` CKAN endpoint.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/DatasetUpdateableData"
                - $ref: "#/components/schemas/DatasetOwnerOrg"
      responses:
        "201":
          description: Successfully created dataset
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetRead"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/OrgNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:datasets"
        - openIdConnect:
            - ryd
            - "ryd:datasets"
      tags:
        - Datasets
  "/datasets/{did}":
    get:
      summary: Get detailed information about a dataset.
      description: Replaces the `/package_show` CKAN endpoint.
      parameters:
        - name: did
          in: path
          description: UUID of dataset.
          required: true
          schema:
            type: string
            format: uuid
            example: ac30e27a-92bd-4f53-8720-16ae9b6aeaab
      responses:
        "200":
          description: Successfully found dataset.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetRead"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/DatasetNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:datasets"
        - openIdConnect:
            - ryd
            - "ryd:datasets"
      tags:
        - Datasets
    patch:
      summary: Update a dataset.
      description: Replaces the `/package_patch` CKAN endpoint.
      parameters:
        - name: did
          in: path
          description: UUID of dataset.
          required: true
          schema:
            type: string
            format: uuid
            example: ac30e27a-92bd-4f53-8720-16ae9b6aeaab
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/DatasetUpdateableData"
      responses:
        "200":
          description: Successfully updated dataset.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetRead"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/DatasetNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:datasets"
            - "ryd:datasets:update"
        - openIdConnect:
            - ryd
            - "ryd:datasets"
            - "ryd:datasets:update"
      tags:
        - Datasets
    delete:
      summary: Delete a dataset.
      description: Replaces the `/package_delete` CKAN endpoint.
      parameters:
        - name: did
          in: path
          description: UUID of dataset.
          required: true
          schema:
            type: string
            format: uuid
            example: ac30e27a-92bd-4f53-8720-16ae9b6aeaab
      responses:
        "200":
          description: Successfully deleted organisation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                status: success
                error: null
                data: null
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/DatasetNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
      security:
        - clientCredentials:
            - ryd
            - "ryd:datasets:delete"
        - openIdConnect:
            - ryd
            - "ryd:datasets:delete"
      tags:
        - Datasets
components:
  # ===============================================================
  #
  # Schemas
  #
  # ===============================================================
  schemas:
    #
    # Base response schema
    #
    BaseResponse:
      type: object
      properties:
        status:
          type: string
        error:
          type: object
          properties:
            status_code:
              type: integer
            error_msg:
              type: string
        data:
          type: object
    #
    # Reporting org schemas
    #
    ReportingOrgUpdateableData:
      type: object
      properties:
        human_readable_name:
          type: string
          example: Aid Agency
        description:
          type: string
          example: >-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua.
        hq_country:
          type: string
          example: CO
        region:
          type: string
          example: "489"
        organisation_type:
          type: string
          example: Regional NGO
        data_portal_url:
          type: string
          format: uri
          example: "https://www.example.org/data-portal"
        exclusions_policy_url:
          type: string
          format: uri
          example: "https://www.example.org/exclusions-policy"
        reporting_source_type:
          type: string
          example: primary_source
          enum:
            - primary_source
            - secondary_source
        default_licence_id:
          type: string
          example: gpl-3.0
        contact_email:
          type: string
          format: email
          example: org.admin@example.org
        address:
          type: string
          example: Fake Address
        phone:
          type: string
          format: phone
          example: 123-4567-8901
        fax:
          type: string
          format: phone
          example: 456-7890-1234
        website:
          type: string
          format: uri
          example: "https://www.example.org/"
    ReportingOrgCreateableData:
      allOf:
        - $ref: "#/components/schemas/ReportingOrgUpdateableData"
        - type: object
          properties:
            short_name:
              type: string
              example: aidagy
            organisation_identifier:
              type: string
              example: CO-ABC-123456
    ReportingOrgReadableData:
      allOf:
        - $ref: "#/components/schemas/ReportingOrgCreateableData"
        - type: object
          properties:
            registry_approved:
              type: boolean
              example: true
            first_publication_date:
              type: string
              format: date-time
              example: "2023-01-15T16:54:14+00:00"
            number_of_published_datasets:
              type: number
              format: int
              example: 12
            created_date:
              type: string
              format: date-time
              example: "2023-01-12T09:42:11+00:00"
      #
      # Org and Dataset action objects
      #
    OrgActionUpdated:
      type: object
      properties:
        action_type:
          type: string
          example: update_metadata
        user_application:
          type: string
          example: IATI Account
        user_name:
          type: string
          example: John Smith
        user_id:
          type: string
          format: uuid
          example: 6423b556-73de-4969-a2f1-91a38bca92b3
        created_date:
          type: string
          format: date-time
          example: "2023-12-25T23:00:12+00:00"
    OrgActionCreated:
      type: object
      properties:
        action_type:
          type: string
          example: created
        user_application:
          type: string
          example: IATI Account
        user_name:
          type: string
          example: John Smith
        user_id:
          type: string
          format: uuid
          example: 6423b556-73de-4969-a2f1-91a38bca92b3
        created_date:
          type: string
          format: date-time
          example: "2023-12-25T23:00:12+00:00"
    DatasetAction:
      type: object
      properties:
        action_type:
          type: string
          example: update_url
        user_application:
          type: string
          example: IATI Account
        user_name:
          type: string
          example: John Smith
        user_id:
          type: string
          format: uuid
          example: 6423b556-73de-4969-a2f1-91a38bca92b3
        created_date:
          type: string
          format: date-time
          example: "2023-12-25T23:00:12+00:00"
    #
    # Reporting org response schemas
    #
    ReportingOrgList:
      properties:
        status:
          type: string
          example: success
        error:
          type: object
          example: null
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
              user_role:
                type: string
                example: editor
              metadata:
                allOf:
                  - $ref: "#/components/schemas/ReportingOrgReadableData"
              reporting_org_actions:
                type: array
                items:
                  $ref: "#/components/schemas/OrgActionUpdated"
    ReportingOrgCreated:
      properties:
        status:
          type: string
          example: success
        error:
          type: object
          example: null
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
              user_role:
                type: string
                example: admin
              metadata:
                allOf:
                  - $ref: "#/components/schemas/ReportingOrgReadableData"
                  - type: object
                    properties:
                      registry_approved:
                        example: false
                      first_publication_date:
                        example: ""
                      number_of_published_datasets:
                        example: 0
    ReportingOrgRead:
      properties:
        status:
          type: string
          example: success
        error:
          type: object
          example: null
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
            user_role:
              type: string
              example: editor
            metadata:
              allOf:
                - $ref: "#/components/schemas/ReportingOrgReadableData"
                - type: object
                  properties:
                    registry_approved:
                      type: boolean
                      example: true
                    first_publication_date:
                      type: string
                      format: date-time
                      example: "2023-01-15T16:54:14+00:00"
                    number_of_published_datasets:
                      type: number
                      format: int
                      example: 12
            reporting_org_actions:
              type: array
              items:
                $ref: "#/components/schemas/OrgActionCreated"
    #
    # User response schemas
    #
    UserList:
      properties:
        status:
          type: string
          example: success
        error:
          type: object
          example: null
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: 6423b556-73de-4969-a2f1-91a38bca92b3
              name:
                type: string
                example: John Smith
              email:
                type: string
                example: admin@example.org
              role:
                type: string
                example: admin
    #
    # Dataset schemas
    #
    DatasetOwnerOrg:
      type: object
      properties:
        owner_organisation_id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
    DatasetUpdateableData:
      type: object
      properties:
        short_name:
          type: string
          example: aidagcy-activity-3
        source_type:
          type: string
          example: primary_source
          enum:
            - primary_source
            - secondary_source
        url:
          type: string
          format: uri
          example: "https://www.example.org/datasets/activity3.xml"
        visibility:
          type: string
          example: public
        licence_id:
          type: string
          example: gpl-3.0
    DatasetReadableData:
      allOf:
        - $ref: "#/components/schemas/DatasetUpdateableData"
        - type: object
          properties:
            last_url_update_date:
              type: string
              format: date-time
              example: "2023-01-01T23:11:21+00:00"
            last_metadata_update_date:
              type: string
              format: date-time
              example: "2022-05-01T13:42:34+00:00"
      #
      # Dataset response schemas
      #
    DatasetList:
      properties:
        status:
          type: string
          example: success
        error:
          type: object
          example: null
        data:
          type: array
          items:
            type: object
            allOf:
              - $ref: "#/components/schemas/DatasetRead"
    DatasetRead:
      type: object
      allOf:
        - $ref: "#/components/schemas/DatasetOwnerOrg"
        - type: object
          properties:
            id:
              type: string
              format: uuid
              example: ac30e27a-92bd-4f53-8720-16ae9b6aeaab
            metadata:
              type: object
              allOf:
                - $ref: "#/components/schemas/DatasetReadableData"
            dataset_actions:
              type: array
              items:
                $ref: "#/components/schemas/DatasetAction"
      # ===============================================================
      #
      # Authentication and authorisation schemes
      #
      # ===============================================================
      # ===============================================================
      #
      # All responses
      #
      # ===============================================================
  responses:
    # 4xx responses
    #
    BadRequest:
      description: Often returned if there is a problem with the access token.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 400
                  error_msg:
                    type: string
                    example: >-
                      There is a problem with your credentials.  If this persists please report error to the provider
                      of the tool you are using to access the IATI Registry.
    Unauthorised:
      description: >-
        Unauthorised access.  The request may not have included an Authorisation header, or may have been missing the
        `Bearer` scheme label, or there may have been some problem with the access token.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 401
                  error_msg:
                    type: string
                    example: >-
                      No authorisation information provided.  If this persists please report error to the provider of
                      the tool you are using to access the IATI Registry.
    Forbidden:
      description: |-
        Forbidden.  The access token may have not have provided authorisation
        to access the API to perform the requested action, or the user did not
        have the appropriate permissions to perform the requested action.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 403
                  error_msg:
                    type: string
                    example: |-
                      No authorisation to perform this operation on this
                      resource.
    OrgNotFound:
      description: Cannot find an organisation with this UUID in the registry.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 404
                  error_msg:
                    type: string
                    example: Organisation UUID is not known in the registry.
    DatasetNotFound:
      description: Cannot find a dataset with this UUID in the registry.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 404
                  error_msg:
                    type: string
                    example: Dataset UUID is not known in the registry.
    NotFound:
      description: Cannot find a record with this UUID in the registry.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 404
                  error_msg:
                    type: string
                    example: UUID is not known in the registry.
    InternalServerError:
      description: Returned for a range of internal server issues.
      content:
        application/json:
          schema:
            properties:
              status:
                type: string
                example: failed
              data:
                example: null
              error:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 500
                  error_msg:
                    type: string
                    example: >-
                      There is a problem with your credentials.  If this persists please report error to the provider
                      of the tool you are using to access the IATI Registry.
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: "https://api.eu.asgardeo.io/t/iati/oauth2/token/.well-known/openid-configuration"
    clientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://api.eu.asgardeo.io/t/iati/oauth2/token"
          scopes:
            ryd: Regular access to the Register Your Data API
            ryd_superadmin: Superadmin access to the Register Your Data API
            "ryd:reporting_org": Read organisation metadata.
            "ryd:reporting_org:create": Create organisations.
            "ryd:reporting_org:update": Update organisation metadata.
            "ryd:reporting_org:delete": Delete an organisation.
            "ryd:reporting_org:users": List the users associated with an organisation.
            "ryd:reporting_org:users:update": Update the users associated with an organisation.
            "ryd:datasets": Create and read.
            "ryd:datasets:update": Update dataset metadata and URLs.
            "ryd:datasets:delete": Delete datasets.
tags:
  - name: Reporting Orgs
    description: |-
      For getting lists of organisations associated with a user, creating
      new organisations, updating and deleting organisation metadata, finding
      all the actions carried out on organisation metadata, finding lists
      of users, and lists of datasets owned by an organisation.
  - name: Datasets
    description: |-
      For getting lists of datasets associated with an organisation, creating
      new datasets, updating metadata and urls, deleting datasets, and finding
      all the actions carried out on dataset metadata/urls.
  - name: Users
    description: For managing the roles users have within organisations.
