---
openapi: 3.0.4
info:
  title: Bulk Data Service API Specification
  description: >-
    This document specifies the format of the Bulk Data Service index files,
    which provide information about the current download status of all IATI XML
    datasets.
  version: 0.9.2
servers:
  - url: 'https://bulk-data.iatistandard.org'
tags:
  - name: datasets
    description: Operations for datasets
  - name: reporting_orgs
    description: Operations for reporting_orgs
paths:
  /datasets-full:
    get:
      operationId: dataset_list_full
      summary: Dataset list with full download status.
      description: >-
        Get the list of datasets with a full set of details about their current
        download status.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref:
                  '#/components/schemas/dataset_check_results_full_detail_list'
              example:
                datasets:
                  - id: 22d82ca0-67de-11f0-90a9-a7bd7f82882f
                    last_known_good_dataset:
                      cached_dataset_xml_etag: '"HXCCHBNTLJWWBB"'
                      cached_dataset_xml_url: >-
                        https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.xml
                      cached_dataset_zip_etag: '"C1362D1244MWNQ"'
                      cached_dataset_zip_url: >-
                        https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.zip
                      content_length: '1612475'
                      downloaded: '2025-06-27T07:31:06+00:00'
                      hash: 041c7dba17b9356be78edc99016d337aa7c33f3a
                      hash_excluding_generated_timestamp: >-
                        738a1ad14dca2451fa89e642b753101dcf57ce2f
                      initial_contents: >-
                        <iati-activities version="2.03"
                        generated-datetime="2025-07-23T20:06:02"><iati-activity
                        xml:lang="en" d
                      server_header_etag: '"KXDMHBNCLJWWUV"'
                      server_header_last_modified: '2025-06-27T07:31:06+00:00'
                      source_url: >-
                        https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
                      verified_on_server: '2025-06-27T07:31:06+00:00'
                    last_update_check: '2025-06-27T07:31:06+00:00'
                    licence_id: string
                    most_recent_get_attempt:
                      datetime: '2025-06-27T07:31:06+00:00'
                      error_details:
                        detailed_message: >-
                          requests.exceptions.ConnectionError:
                          HTTPConnectionPool(host='www.iatistandard.com',
                          port=80): Max retries exceeded with url: / (Caused by
                          NameResolutionError("<urllib3.connection.HTTPConnection
                          object at 0x74b4aecaa9c0>: Failed to resolve
                          'www.iatistandard.com' ([Errno -2] Name or service not
                          known)"))
                        error_type: connection_error
                        http_headers: {}
                        http_method: GET
                        http_reason: Not Found
                        http_status: 404
                        source_url: >-
                          https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
                        summary_message: >-
                          Download attempt failed due to connection timeout.
                      error_occurred: true
                      http_status: 200
                    most_recent_head_attempt:
                      datetime: '2025-06-27T07:31:06+00:00'
                      error_details:
                        detailed_message: >-
                          requests.exceptions.ConnectionError:
                          HTTPConnectionPool(host='www.iatistandard.com',
                          port=80): Max retries exceeded with url: / (Caused by
                          NameResolutionError("<urllib3.connection.HTTPConnection
                          object at 0x74b4aecaa9c0>: Failed to resolve
                          'www.iatistandard.com' ([Errno -2] Name or service not
                          known)"))
                        error_type: connection_error
                        http_headers: {}
                        http_method: HEAD
                        http_reason: Not Found
                        http_status: 404
                        source_url: >-
                          https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
                        summary_message: >-
                          Download attempt failed due to connection timeout.
                      error_occurred: true
                      http_status: 200
                    reporting_org_id: de576bb9-5f2b-4d43-a570-53ab3b8bb9b8
                    reporting_org_short_name: aidagcy
                    short_name: aidagcy-activity-3
                    source_url: >-
                      https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
                index_created: '2025-06-27T07:31:06+00:00'
                index_created_unix_timestamp: 1751005866
      tags:
        - datasets
  /datasets-minimal:
    get:
      operationId: dataset_list_minimal
      summary: Dataset list with baisc download status information.
      description: >-
        Get the list of datasets with a minimal set of details about their
        current download status.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref:
                  '#/components/schemas/dataset_check_results_minimal_detail_list'
              example:
                datasets:
                  - id: 22d82ca0-67de-11f0-90a9-a7bd7f82882f
                    last_known_good_dataset:
                      cached_dataset_xml_url: https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.xml
                      cached_dataset_zip_url: https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.zip
                      downloaded: '2025-06-27T07:31:06+00:00'
                      hash: 041c7dba17b9356be78edc99016d337aa7c33f3a
                      hash_excluding_generated_timestamp: 738a1ad14dca2451fa89e642b753101dcf57ce2f
                      verified_on_server: '2025-06-27T07:31:06+00:00'
                    last_update_check: '2025-06-27T07:31:06+00:00'
                    licence_id: string
                    reporting_org_id: de576bb9-5f2b-4d43-a570-53ab3b8bb9b8
                    reporting_org_short_name: aidagcy
                    short_name: aidagcy-activity-3
                    source_url: https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
                index_created: '2025-06-27T07:31:06+00:00'
                index_created_unix_timestamp: 0
      tags:
        - datasets
  /reporting-orgs:
    get:
      operationId: reporting_orgs
      summary: List of reporting orgs.
      description: Get the list of reporting orgs with registration information.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reporting_orgs'
              example:
                reporting_orgs:
                  - created_date: '2023-08-27T07:31:06+00:00'
                    data_portal_url: https://www.example.org/data-portal
                    default_licence_id: gpl-3.0
                    description: >-
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                      do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua.
                    exclusions_policy_url: >-
                      https://www.example.org/exclusions-policy
                    first_publication_date: '2025-06-27T07:31:06+00:00'
                    hq_country: GB
                    human_readable_name: Aid Agency
                    id: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
                    organisation_identifier: CO-ABC-123456
                    organisation_type: '23'
                    region: '889'
                    reporting_source_type: primary-source
                    short_name: aidagcy
                    website: https://www.example.org/
                index_created: '2025-06-27T07:31:06+00:00'
                index_created_unix_timestamp: 1751005866
      tags:
        - reporting_orgs
components:
  schemas:
    reporting_orgs:
      description: A list of reporting orgs and the date it was generated.
      type: object
      properties:
        reporting_orgs:
          type: array
          items:
            $ref: '#/components/schemas/reporting_org'
        index_created:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: false
        index_created_unix_timestamp:
          type: integer
          format: int
          example: 1751005866
          nullable: false
      required:
        - index_created
        - index_created_unix_timestamp
        - reporting_orgs
      example:
        reporting_orgs:
          - created_date: '2023-08-27T07:31:06+00:00'
            data_portal_url: https://www.example.org/data-portal
            default_licence_id: gpl-3.0
            description: >-
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
              do eiusmod tempor incididunt ut labore et dolore magna
              aliqua.
            exclusions_policy_url: >-
              https://www.example.org/exclusions-policy
            first_publication_date: '2025-06-27T07:31:06+00:00'
            hq_country: GB
            human_readable_name: Aid Agency
            id: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
            organisation_identifier: CO-ABC-123456
            organisation_type: '23'
            region: '889'
            reporting_source_type: primary-source
            short_name: aidagcy
            website: https://www.example.org/
        index_created: '2025-06-27T07:31:06+00:00'
        index_created_unix_timestamp: 1751005866
    reporting_org:
      description: An IATI Registry reporting_org record (without contact info).
      type: object
      properties:
        created_date:
          type: string
          format: date-time
          example: '2023-08-27T07:31:06+00:00'
          nullable: true
        data_portal_url:
          type: string
          format: uri
          example: 'https://www.example.org/data-portal'
          nullable: true
        default_licence_id:
          type: string
          example: gpl-3.0
          nullable: true
        description:
          type: string
          example: >-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          nullable: true
        exclusions_policy_url:
          type: string
          format: uri
          example: 'https://www.example.org/exclusions-policy'
          nullable: true
        first_publication_date:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
        hq_country:
          description: >-
            This is a codelist field. Valid values come from the code list:
            https://iatistandard.org/en/iati-standard/203/codelists/country/
          type: string
          example: GB
          nullable: true
        human_readable_name:
          type: string
          example: Aid Agency
          nullable: false
        id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
          nullable: false
        iati_identifier:
          description: >-
            This field is now deprecated in favour of `organisation_identifier`
            which is the terminology used in the Standard for this value. This
            field and the `organisation_identifier` field will always be
            identical.
          type: string
          deprecated: true
          example: CO-ABC-123456
          nullable: true
        organisation_identifier:
          type: string
          example: CO-ABC-123456
          nullable: true
        organisation_type:
          description: >-
            This is a codelist field. Valid values come from the code list:
            https://iatistandard.org/en/iati-standard/203/codelists/organisationtype/
          type: string
          example: '23'
          nullable: true
        region:
          description: >-
            This is a codelist field. Valid values come from the code list:
            https://iatistandard.org/en/iati-standard/203/codelists/region/
          type: string
          example: '889'
          nullable: true
        reporting_source_type:
          type: string
          example: primary-source
          enum:
            - primary-source
            - secondary-source
          nullable: true
        short_name:
          type: string
          example: aidagcy
          nullable: false
        website:
          type: string
          format: uri
          example: 'https://www.example.org/'
          nullable: true
      required:
        - created_date
        - data_portal_url
        - default_licence_id
        - description
        - exclusions_policy_url
        - first_publication_date
        - hq_country
        - human_readable_name
        - id
        - organisation_identifier
        - organisation_type
        - region
        - reporting_source_type
        - short_name
        - website
    dataset_check_results_full_detail_list:
      description: A list of datasets with full download check results.
      type: object
      properties:
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/dataset_check_result_full_details'
        index_created:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: false
        index_created_unix_timestamp:
          type: integer
          format: int
          example: 1751005866
          nullable: false
      required:
        - datasets
        - index_created
        - index_created_unix_timestamp
    dataset_check_results_minimal_detail_list:
      description: A list of datasets with basic download status information.
      type: object
      properties:
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/dataset_check_result_minimal_details'
        index_created:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: false
        index_created_unix_timestamp:
          type: integer
          format: int
          nullable: false
      required:
        - datasets
        - index_created
        - index_created_unix_timestamp
    dataset_check_result_full_details:
      description: A dataset record with full details of download status.
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 22d82ca0-67de-11f0-90a9-a7bd7f82882f
        last_known_good_dataset:
          $ref: '#/components/schemas/dataset_download_full_details'
        last_update_check:
          description: >-
            The date time at which the dataset file was last checked, whether
            that check involved a `HEAD` request, a full download attempt, or
            both.

            This field is updated regardless of the result.
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
        licence_id:
          type: string
          nullable: true
        most_recent_get_attempt:
          $ref: '#/components/schemas/dataset_get_request_attempt_result'
        most_recent_head_attempt:
          $ref: '#/components/schemas/dataset_head_request_attempt_result'
        reporting_org_id:
          type: string
          format: uuid
          example: de576bb9-5f2b-4d43-a570-53ab3b8bb9b8
          nullable: false
        reporting_org_short_name:
          type: string
          example: aidagcy
          nullable: false
        short_name:
          type: string
          example: aidagcy-activity-3
          nullable: false
        source_url:
          type: string
          format: uri
          example:
            'https://www.example.com/files/aidagcy/aidagcy-activity-file.xml'
          nullable: false
      required:
        - id
        - last_known_good_dataset
        - last_update_check
        - licence_id
        - most_recent_get_attempt
        - most_recent_head_attempt
        - reporting_org_id
        - reporting_org_short_name
        - short_name
        - source_url
    dataset_check_result_minimal_details:
      description: A dataset record with basic details of download status.
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 22d82ca0-67de-11f0-90a9-a7bd7f82882f
        last_known_good_dataset:
          $ref: '#/components/schemas/dataset_download_minimal_details'
        last_update_check:
          description: >-
            This field is updated every time the Bulk Data Service checks the
            dataset, regardless of whether a full download was attempted and
            regardless of the result.
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
        licence_id:
          type: string
          nullable: true
        reporting_org_id:
          type: string
          format: uuid
          example: de576bb9-5f2b-4d43-a570-53ab3b8bb9b8
          nullable: false
        reporting_org_short_name:
          type: string
          example: aidagcy
          nullable: false
        short_name:
          type: string
          example: aidagcy-activity-3
          nullable: false
        source_url:
          type: string
          format: uri
          example:
            'https://www.example.com/files/aidagcy/aidagcy-activity-file.xml'
          nullable: false
      required:
        - id
        - last_known_good_dataset
        - last_update_check
        - licence_id
        - reporting_org_id
        - reporting_org_short_name
        - short_name
        - source_url
    dataset_download_full_details:
      description: Details of a successful download of a dataset.
      type: object
      properties:
        cached_dataset_xml_etag:
          type: string
          example: '"HXCCHBNTLJWWBB"'
          nullable: true
        cached_dataset_xml_url:
          description: >-
            The URL of the cached XML copy of the dataset file. A cached copy is
            saved only if the Bulk Data Service successfully downloaded an IATI
            XML file.

            If the XML file becomes unavailable on the source server, the cached
            XML file is stored for ~72 hours before being removed.

            If the reporting organisation unregisters the XML file from the IATI
            Registry, the cached copy is removed as soon as the change is picked
            up.
          type: string
          format: uri
          example:
            'https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.xml'
          nullable: true
        cached_dataset_zip_etag:
          type: string
          example: '"C1362D1244MWNQ"'
          nullable: true
        cached_dataset_zip_url:
          description: >-
            A copy of the cached dataset that has been compressed using the ZIP
            format.
          type: string
          format: uri
          example:
            'https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.zip'
          nullable: true
        content_length:
          type: string
          format: int
          example: '1612475'
          nullable: true
        downloaded:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
        hash:
          description: A SHA1 hash of the entire contents of the dataset file.
          type: string
          example: 041c7dba17b9356be78edc99016d337aa7c33f3a
          nullable: true
        hash_excluding_generated_timestamp:
          description: >-
            A SHA1 hash of the contents of the dataset file interpreted as a
            string after any content matching the following regular expression
            has been removed: `generated-datetime="[^"]+"`.

            Note: because applying the removal of content matching the regular
            expression requires a string, the contents of the dataset file is
            decoded first, according to what the `chardet` Python library
            determines is the dataset's character set encoding (e.g., UTF-8,
            UTF-16). But because character set encoding determination cannot be
            guaranteed to be correct, and because Python's string encoding
            library may not reinsert a BOM where there was on when re-encoding,
            the value of this hash field is not guaranteed to be identical to
            the hash of the file minus the content matched by
            `generated-datetime="[^"]+"` when generated using other methods
            (e.g., other libraries or programming languages).
          type: string
          example: 738a1ad14dca2451fa89e642b753101dcf57ce2f
          nullable: true
        initial_contents:
          type: string
          example: >-
            <iati-activities version="2.03"
            generated-datetime="2025-07-23T20:06:02"><iati-activity
            xml:lang="en" d
          nullable: true
        server_header_etag:
          description: >-
            The contents of the `ETag` header on the source server (if one is
            present).
          type: string
          example: '"KXDMHBNCLJWWUV"'
          nullable: true
        server_header_last_modified:
          description: >-
            The contents of the `Last-Modified` header on the source server (if
            one is present).
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
        source_url:
          type: string
          format: uri
          example:
            'https://www.example.com/files/aidagcy/aidagcy-activity-file.xml'
          nullable: true
        verified_on_server:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
      required:
        - cached_dataset_xml_etag
        - cached_dataset_xml_url
        - cached_dataset_zip_etag
        - cached_dataset_zip_url
        - content_length
        - downloaded
        - hash
        - hash_excluding_generated_timestamp
        - initial_contents
        - server_header_etag
        - server_header_last_modified
        - source_url
        - verified_on_server
    dataset_download_minimal_details:
      description: Minimal details of a successful download of a dataset.
      type: object
      properties:
        cached_dataset_xml_url:
          type: string
          format: uri
          example:
            'https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.xml'
          nullable: true
        cached_dataset_zip_url:
          type: string
          format: uri
          example:
            'https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.zip'
          nullable: true
        downloaded:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
        hash:
          type: string
          example: 041c7dba17b9356be78edc99016d337aa7c33f3a
          nullable: true
        hash_excluding_generated_timestamp:
          type: string
          example: 738a1ad14dca2451fa89e642b753101dcf57ce2f
          nullable: true
        verified_on_server:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
      required:
        - cached_dataset_xml_url
        - cached_dataset_zip_url
        - downloaded
        - hash
        - hash_excluding_generated_timestamp
        - verified_on_server
    dataset_head_request_attempt_result:
      description: >-
        An object which details the results of a HEAD attempt by the Bulk Data
        Service.
      type: object
      properties:
        datetime:
          description: >-
            The time of the `HEAD` request was made. `HEAD` requests are only
            made when the `source_url` is unchanged and the dataset has been
            successfully downloaded in the last ~72 hours. This means that the
            time of the most recent `HEAD` request may not be the same as the
            `last_update_check`.
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
        error_details:
          description: >-
            Provides details of any error that occurred.
          type: object
          nullable: false
          properties:
            detailed_message:
              description: >-
                A detailed error message, often produced by the relevant
                component library.
              type: string
              example: >-
                requests.exceptions.ConnectionError:
                HTTPConnectionPool(host='www.iatistandard.com', port=80): Max
                retries exceeded with url: / (Caused by
                NameResolutionError("<urllib3.connection.HTTPConnection object
                at 0x74b4aecaa9c0>: Failed to resolve 'www.iatistandard.com'
                ([Errno -2] Name or service not known)"))
              nullable: true
            error_type:
              description: >-
                The type of error that occurred. `other_error` indicates any
                connection error not listed that resulted in there not being a
                valid HTTP response.
              type: string
              enum:
                - connection_error
                - connection_timeout
                - too_many_redirects
                - ssl_error
                - other_error
                - http_non_200
              nullable: true
            http_headers:
              type: object
              nullable: true
            http_method:
              type: string
              enum:
                - HEAD
              nullable: true
            http_reason:
              type: string
              example: Not Found
              nullable: true
            http_status:
              type: integer
              example: 404
              nullable: true
            source_url:
              description: >-
                The URL which caused the error. Note that this may not be the
                same as the current value of `source_url` because if the
                dataset's registered `source_url` is updated then the Bulk Data
                Service proceeds straight to a full download attempt and does
                not attempt a `HEAD` request.
              type: string
              format: uri
              example:
                'https://www.example.com/files/aidagcy/aidagcy-activity-file.xml'
              nullable: true
            summary_message:
              description: A succinct error message from the Bulk Data Service.
              type: string
              example: Download attempt failed due to connection timeout.
              nullable: true
          required:
            - detailed_message
            - error_type
            - http_method
            - http_reason
            - http_status
            - http_headers
            - source_url
            - summary_message
        error_occurred:
          description: >-
            Indicates whether or not the `HEAD` resulted in an error. It will be
            true if either there was a problem completing the HTTP connection,
            or if the HTTP response was non-200. False implies `http_status` is
            200.
          type: boolean
          nullable: true
        http_status:
          description: >-
            The 'http_status' field provides the HTTP status code regardless of
            outcome.
          type: integer
          example: 200
      required:
        - datetime
        - error_details
        - error_occurred
        - http_status
    dataset_get_request_attempt_result:
      description: >-
        An object which details the results of a GET attempt by the Bulk
        Data Service or Data Downloader.
      type: object
      properties:
        datetime:
          description: >-
            The date time at which the last full download of the dataset file
            was attempted.

            It may differ from the `last_known_good_dataset.verified_on_server`
            field because the latter is updated when a successful `HEAD` request
            confirms the dataset file remains on the server unchanged.
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
        error_details:
          description: >-
            Provides details of any error that occurred.
          type: object
          nullable: false
          properties:
            detailed_message:
              description: >-
                A detailed error message, often produced by the relevant
                component library.
              type: string
              example: >-
                requests.exceptions.ConnectionError:
                HTTPConnectionPool(host='www.iatistandard.com', port=80): Max
                retries exceeded with url: / (Caused by
                NameResolutionError("<urllib3.connection.HTTPConnection object
                at 0x74b4aecaa9c0>: Failed to resolve 'www.iatistandard.com'
                ([Errno -2] Name or service not known)"))
              nullable: true
            error_type:
              description: >-
                Gives details of the error encountered when making the `GET`
                request. The value `not_iati_content` indicates that a file was
                succcessfully downloaded (such that `http_status` will be 200)
                but that it was not an IATI XML file.
              type: string
              enum:
                - connection_error
                - connection_timeout
                - too_many_redirects
                - ssl_error
                - other_error
                - http_non_200
                - not_iati_content
              nullable: true
            http_headers:
              type: object
              nullable: true
            http_method:
              type: string
              enum:
                - GET
              nullable: true
            http_reason:
              type: string
              example: Not Found
              nullable: true
            http_status:
              description: >-
                **Note:** A status of 200 indicates a successful download of
                some file or other, but the download result could still be in an
                error state if the file downloaded is not a valid IATI XML file.
                For this reason, the `error_occurred` field on the parent object
                should be used for determining error status.
              type: integer
              example: 404
              nullable: true
            source_url:
              description: >-
                The url which produced the `GET` error. Note that this may not
                be the same as the current value of `source_url` because the
                `source_url` may have recently been updated and there may not
                yet be any download results for the new url.
              type: string
              format: uri
              example:
                'https://www.example.com/files/aidagcy/aidagcy-activity-file.xml'
              nullable: true
            summary_message:
              description: A succinct error message from the Bulk Data Service.
              type: string
              example: Download attempt failed due to connection timeout.
              nullable: true
          required:
            - detailed_message
            - error_type
            - http_method
            - http_reason
            - http_status
            - http_headers
            - source_url
            - summary_message
        error_occurred:
          description: >-
            Indicates whether or not the `GET` request resulted in a
            _**successful download of an IATI XML file**_. This means that an
            HTTP status of 200 does not necessarily indicate success. For this
            reason, this field should be used to determine success status.
          type: boolean
          nullable: true
        http_status:
          description: >-
            An `http_status` of 200 does not necessarily mean an IATI
            dataset has been successfully downloaded, because the file
            downloaded may not have been an IATI XML file. For this reason, the
            `error_occurred` field should be used to determine success.
          type: integer
          example: 200
          nullable: true
      required:
        - datetime
        - error_details
        - error_occurred
        - http_status
